version: '3.4'

services:
  instagram_api.presentation:
    image: ${DOCKER_REGISTRY-}instagramapipresentation
    build:
      context: .
      dockerfile: 1-Presentation/Dockerfile
    ports:
        - "8000:8000"
        - "8001:8001"
  
  api-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: api-database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sUPERSECURE!!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/api-database:/var/opt/mssql/data
